// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  books_grid: dynamic(() => import("./BooksGrid")),
  hero: dynamic(() => import("./Hero")),
};
